# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: pet-connect
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing  # ALB가 외부에서 접근 가능하도록 설정
#     alb.ingress.kubernetes.io/target-type: ip          # 타겟을 IP로 설정
#     alb.ingress.kubernetes.io/group.name: pet-connect-group  # ALB 그룹 이름 (원하는 대로 설정)
# spec:
#   ingressClassName: alb  # ALB Ingress Controller를 사용한다고 명시
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: pet-connect-service
#             port:
#               number: 80
